services:
  - type: web
    name: xarala-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn xarala_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://xarala:password@localhost:5432/xarala
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://votre-frontend.netlify.app"