# Generated by Django 5.2.4 on 2025-07-17 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcamp',
            options={'ordering': ['next_session'], 'verbose_name': 'Bootcamp', 'verbose_name_plural': 'Bootcamps'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='bootcamp',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ce bootcamp est-il actuellement disponible ?', verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leads', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='description',
            field=models.TextField(help_text='Détails complets du programme', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='duration',
            field=models.CharField(help_text='Ex: 12 semaines, 3 mois', max_length=50, verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='next_session',
            field=models.DateField(help_text='Date de début de la prochaine session', verbose_name='Prochaine session'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix en FCFA', max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='title',
            field=models.CharField(help_text='Titre complet du bootcamp', max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='bootcamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='bootcamps.bootcamp', verbose_name='Bootcamp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, help_text='Pourquoi êtes-vous intéressé ?', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format: 77|76|70|78 suivi de 7 chiffres', regex='^(77|76|70|78|75|33)\\d{7}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('CONTACTED', 'Contacté'), ('REGISTERED', 'Inscrit'), ('REJECTED', 'Non intéressé')], default='NEW', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='bootcamps_l_status_4ec643_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='bootcamps_l_created_0e0af7_idx'),
        ),
    ]
